apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pgadmin-role-binding
  labels:
    postgres-operator.crunchydata.com/control-plane: postgres-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pgadmin-role
subjects:
- kind: ServiceAccount
  name: pgadmin