apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pgadmin-role
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - pods/exec
  verbs:
  - create
  - get
